#!/bin/bash
#
# Usage:
#
#   run-class-gdx <QualifiedGameClassName>
#
# "gdx-setup" is basically "java -jar gdx-setup.jar "$@""
#
# Use of 'sed' with '-i' as done here kinda means it needs
# to be modified for use on e.g. linux.
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
python3 "$DIR/scripts/run-class-gdx.py" "$@"
