#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rm -rf out/generated && \
"$DIR/run-assetpkg" --use-java-default-roots support/tests -o out/generated && \
mvn -q clean package
