#!/bin/bash
#
# Usage:
#
#   run-class-gdx <QualifiedGameClassName>
#
# "gdx-setup" is basically "java -jar gdx-setup.jar "$@""
#
# Use of 'sed' with '-i' as done here kinda means it needs
# to be modified for use on e.g. linux.
#
mkdir -p out && \
rm -rf out/gdx && \
gdx-setup --dir out/gdx \
    --name Sample \
    --package crossj.hacks.gameio \
    --mainClass Main \
    --excludeModules "android;ios" && \
rm -rf out/gdx/core/src/crossj && \
cp -r support/java/* out/gdx/core/src && \
cp -r support/shared/* out/gdx/core/src && \
cp -r support/gdx/* out/gdx/core/src && \
sed -i '' "s/crossj\.hacks\.gameio\.placeholder\.GamePlaceholder/$1/" \
    out/gdx/core/src/crossj/hacks/gameio/Main.java && \
rm -rf ~/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.11/ && \
sed -i '' \
    's/sourceCompatibility = 1\.7/sourceCompatibility = 11/' \
    $(find out/gdx/ -name "build.gradle") && \
(cd out/gdx && ./gradlew desktop:run)
